### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by davi317** [mengento/Magento2_Order_Item_Thumbnail#1]
Magento Community Edition 2.0.7 安装错误！崩溃！

请问多店铺语言切换不了，这样的问题怎么处理！谢谢！
![eccbbccc-dd58-11e5-8500-1b140ca41d2e](https://cloud.githubusercontent.com/assets/17508700/15766874/bd73ad22-2975-11e6-90e0-46ce10917383.jpg)

**Comment by mengento** [comment]
这个插件是后台订单显示产品图片,你的问题不相关
